### ISSUE TITLE
Some emoji break the overview definition

### ISSUE THREAD

**Issue by zblesk** [JackGruber/joplin-plugin-note-overview#43]
I have a definiton like this:

```
<!-- note-overview-plugin
search: tag:"some tag"
fields: title, breadcrumb, tags, updated_time
alias: title AS Nazov, updated_time AS 💾🕒, tags as #️⃣ Tagy, breadcrumb AS Umiesnenie,
sort: updated_time DESC
-->
```

When the overview is refreshed, everything from #️⃣ until the end of that line is deleted. 
The other emoji in that line cause no problems, and neither does changing the order of fields in the `alias` line. 

I'm running an up-to-date version of the plugin under Joplin for Desktop 2.6.10 on Windows 10.

**Comment by JackGruber** [comment]
Ok there are tow problems:

**1)** Your keyword `as` is lower case, for this a fix will be implemented
**2)** The emoji #️⃣ is special, because it is in Hex: `233F3F`, and the staring 23 is a `#` witch starts a comment in YAML. 
The comment sign is the reason why everything after that also disappears, if a character other than a space is placed in front of the the comment character, this will not be interpreted as a comment. But the best way is to enclose the alias text in quotes `"`.

```
<!-- note-overview-plugin
search: tag:emoji
fields: title, breadcrumb, tags, updated_time
alias: "title AS Nazov, updated_time AS 💾🕒, tags AS #️⃣ Tagy, breadcrumb AS Umiesnenie"
sort: updated_time DESC
-->
```
![grafik](https://user-images.githubusercontent.com/24863925/148679527-a4d3ec1c-7e30-4c0b-ab8d-729bbbc373ad.png)

**Comment by zblesk** [comment]
Ah. I have tried things like quotes around "#️⃣ Tagy", like you have to do in the `search` sometimes. Didn't try enclosing the whole thing.

I don't understand the 'as' comment, but since that bit works as it is, I guess it doesn't matter that much.

Thanks!
