### ISSUE TITLE
Enable Single Note Update

### ISSUE THREAD

**Issue by Ghalko** [JackGruber/joplin-plugin-note-overview#49]
I have weekly notes that I am using the note overview to generate lists of tickets and other notes that have been created or updated during the week. I use dates to bracket these updates and creates, however, previous weeks are losing information because they are also being re-run.

#46 may relate, if all notes are being updated at once.

I see two options:
- I am not seeing the documentation for how to run a single note update, nor can I discover it, but it is there.
- Add a button in the menu bar or in the right-click dialog that limits the creation/update of note overviews to the current note.

Thanks!

**Comment by JackGruber** [comment]
All note overviews are always updated, there is no function to update only one of them.

The Plugin throttle for too many API calls was was only present in beta 2.7.6 of joplin and was reintroduced in the current beta 2.8. But in a different version and is currently also still adjusted. 

>I use dates to bracket these updates and creates, however, previous weeks are losing information because they are also being re-run.

If you don't want the overview note to be updated anymore, because the information is no longer available on a search and an update would use display wrong/outdatade data, than you have to delete the note-overview block to prvend updating of this note.

**Comment by ruzoka** [comment]
To whom it may concern,

is there a possibility to just search in a subnotebook? 
What would be an alternative if that is not possible, tag the notes/to dos with the name of the subnotebook, or is there another workaround?

Thanks!
