### ISSUE TITLE
Feature Request: Smaller Codeblock areas

### ISSUE THREAD

**Issue by rtakehara** [JackGruber/joplin-plugin-note-overview#54]
I use note overview to filter certain notes dynamically, and I prefer to use only the markdown editor for everything, but I assume this would be useful for other uses and people.

I would like to request some way for the code block to use less lines, either by including a retract/expand arrow in the editor, or by allowing everything to be viewed in the same line, as these examples:

**How it is** I usedcss to make it less proeminent
![Screenshot (97)](https://user-images.githubusercontent.com/49849179/189198563-a0319195-bb10-4175-bd55-1881f415fffb.png)

**Idea 1** would be to add a retract/expand arrow, this would keep YAML syntax intact
![Screenshot (98)](https://user-images.githubusercontent.com/49849179/189198541-3895fe29-d8ad-47bc-9c5e-ab2deab1551c.png)

**Idea 2** is to allow everything in a single line
![Screenshot (99)](https://user-images.githubusercontent.com/49849179/189198499-3e899d1c-a5b3-45c0-a259-24e5e0331a88.png)

I have no idea if any of these are possible, or how difficult they are.

If all is impossible, maybe a way to add css class to the text inside `<!---` and `--->` so I could make a css to disable it, so when there are no comment tags it is all visible, but once the comment is complete, it would show just `<!------>` or something

**Comment by JackGruber** [comment]
Since the markup language is YAML, no one-liner will work, a css customization I will not include in the plugin.
Therefore the option with retract/expand is also no option. 

To read just use the viewer instead of the editor, then the code block is not visible. 
This can be automated with the plugin [Joplin Persistent Editor Layout](https://github.com/benji300/joplin-persistent-layout)

**Comment by rtakehara** [comment]
ah, very interesting, that could work well
