### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by Galliver7** [JackGruber/joplin-plugin-note-overview#63]
Hi,

I really love this plugin.
I would like to become a Github sponsor for the future of this plugin, could you possibly enable this feature?

**Comment by JackGruber** [comment]
Since I do this in my spare time and don't want to bother with German tax law, I haven't activated this option anywhere.
These "donations", which in Germany are not donations but additional income, would have to be taxed. 

But thank you for liking the plugin. Feel free to donate directly to Joplin.
